# Generated by Django 5.0.6 on 2024-07-11 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_attribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(null=True)),
                ("is_digital", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("IS", "In Stock"),
                            ("OOS", "Out of stock"),
                            ("BO", "Back Ordered"),
                        ],
                        default="OOS",
                        max_length=3,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.category",
                    ),
                ),
                (
                    "seasonal_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.seasonalevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product_ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.producttype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.ManyToManyField(
                related_name="product_type",
                through="inventory.Product_ProductType",
                to="inventory.producttype",
            ),
        ),
        migrations.RunSQL("""
            ALTER TABLE inventory_product
            ADD CONSTRAINT inventory_product_chk_empty_name
            CHECK (name <> '' AND name is NOT NULL)  
        """),
        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION lowercase_name_trigger()
            RETURNS TRIGGER AS $$
            BEGIN
                NEW.name := LOWER(NEW.name);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER product_lowercase_name_trigger
            BEFORE INSERT OR UPDATE ON inventory_product
            FOR EACH ROW
            EXECUTE FUNCTION lowercase_name_trigger();
        """),
        migrations.RunSQL("""
            ALTER TABLE inventory_product
            ADD CONSTRAINT inventory_product_chk_slug_format
            CHECK (slug ~ '^[a-z0-9_-]+$');
        """),
    ]
