# Generated by Django 5.0.6 on 2024-07-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_value", models.CharField(max_length=100)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.attribute",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_attribute_value",
            },
        ),
        migrations.RunSQL("""
            ALTER TABLE inventory_attribute_value
            ADD CONSTRAINT inventory_attribute_value_chk_unique_name_level
            UNIQUE (attribute_id, attribute_value);
        """),
    ]
