# Generated by Django 5.0.6 on 2024-07-11 13:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_attribute_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sku", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("stock_qty", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=False)),
                ("order", models.IntegerField()),
                ("weight", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_product_line",
            },
        ),
        migrations.CreateModel(
            name="ProductLine_AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.attributevalue",
                    ),
                ),
                (
                    "product_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.productline",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productline",
            name="attribute_values",
            field=models.ManyToManyField(
                related_name="attribute_values",
                through="inventory.ProductLine_AttributeValue",
                to="inventory.attributevalue",
            ),
        ),
        migrations.RunSQL("""
            ALTER TABLE inventory_product_line
            ADD CONSTRAINT inventory_product_line_chk_price_positive
            CHECK (price > 0);
        """),
        migrations.RunSQL("""
            ALTER TABLE inventory_product_line
            ADD CONSTRAINT inventory_product_line_chk_stock_positive
            CHECK (stock_qty >= 0);
        """),
    ]
