# Generated by Django 5.0.6 on 2024-07-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_product_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alternative_text", models.CharField(max_length=100)),
                ("url", models.ImageField(upload_to="")),
                ("order", models.IntegerField()),
                (
                    "product_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.productline",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_product_image",
            },
        ),
        migrations.RunSQL("""
            ALTER TABLE inventory_product_image
            ADD CONSTRAINT inventory_product_image_chk_unique_product_order
            UNIQUE (product_line_id, "order");
        """),
    ]
